import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';

void main() {
  // dart:js_interop is not loadable on the VM test platform, so the legacy
  // generated-bindings surface lives in a fixture that this test analyzes.
  // If the analyzer reports anything, the pre-0.0.15 generated-file API has
  // been broken.
  final fixture = p.join('test', 'fixtures', 'legacy_bindings_v0_0_14.dart');

  test('bindings generated by ffigen_js <= 0.0.14 still analyze cleanly',
      () async {
    final result = await Process.run(Platform.resolvedExecutable,
        ['analyze', fixture],
        workingDirectory: Directory.current.path,
        stdoutEncoding: utf8,
        stderrEncoding: utf8);

    expect(
      result.stderr.toString(),
      isEmpty,
      reason: 'dart analyze crashed on the legacy fixture',
    );
    expect(
      result.exitCode,
      0,
      reason: 'legacy fixture no longer analyzes cleanly:\n'
          '${result.stdout}',
    );
  });
}
