name: ffigen_js_example

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  ffigen_js:
    path: '../'

dev_dependencies:  
  lints: ^2.0.1
  ffigen: ^20.0.0
  test: ^1.25.6
  ffi: ^2.1.0
  hooks: ^2.0.2
  native_toolchain_c: ^0.19.2
