// Regression guard: bindings generated by ffigen_js <= 0.0.14 must keep
// compiling against the current runtime. The file below reproduces, verbatim
// in shape, the wrapper prelude and the call patterns the old writer.dart
// emitted (ambient `NativeLibrary.instance` everywhere, `implements
// JSObject` wrapper, `globalContext.getProperty` init). If this file stops
// compiling, single-module apps with pre-existing generated files break.
//
// Compile-only fixture: dart:js_interop is unavailable on the VM test
// platform, so this file cannot be imported by a VM test; the companion test
// analyzes it instead.
//
// ignore_for_file: type=lint
import 'dart:js_interop';
import 'dart:js_interop_unsafe';
import 'dart:typed_data';

import 'package:ffigen_js/ffigen_js.dart';

// ignore_for_file: unused_local_variable, unused_element

extension type GeneratedBindings(NativeLibrary _) implements JSObject {
  static GeneratedBindings get instance =>
      NativeLibrary.instance as GeneratedBindings;

  static void initBindings(String moduleName) {
    var lib = globalContext.getProperty(moduleName.toJS);
    if (lib == null) {
      throw Exception("Failed to find JS module ${moduleName}");
    }
    NativeLibrary.instance = lib as NativeLibrary;
  }

  external JSNumber _addOne(JSNumber value);
  external Pointer<Int32> _GLOBALINT;
}

int addOne(int value) =>
    GeneratedBindings.instance._addOne(value.toJS).toDartInt;

int get globalInt => NativeLibrary.instance.getValue(
    GeneratedBindings.instance._GLOBALINT, 'i32').toDartInt;

final class OldStruct extends Struct {
  double get x {
    final addr = Pointer<OldStruct>(this.address.addr + 0);
    final value = NativeLibrary.instance.getValue(addr, 'float');
    return value.toDartDouble;
  }

  set x(double val) {
    NativeLibrary.instance.setValue(
        Pointer<OldStruct>(this.address.addr + 0), val.toJS, 'float');
  }

  static Pointer<OldStruct> stackAlloc() =>
      Pointer<OldStruct>(NativeLibrary.instance.stackAlloc<OldStruct>(4));

  OldStruct(super.address);
}

void legacyAmbientSurface() {
  GeneratedBindings.initBindings('module');
  NativeLibrary.initBindings('module');

  final ptr = 'hello'.toNativeUtf8();
  ptr.toDartString();

  final list = makeUint8List(4);
  list[0] = 1;

  final i32 = Int32.stackAlloc(1);
  i32.setValue(11);
  i32.getValue();

  final floats = Float32List(2);
  floats.address;
  malloc<Uint8>(16);
  stackAlloc<Uint8>(8);

  final heap = globalContext.getProperty('module'.toJS) as NativeLibrary;
  heap.getValueBigInt(Pointer<Char>.fromAddress(0), 'i64');
  heap.HEAPF32;
  heap.stackSave();
}
